### ISSUE TITLE
Show link status next to the link itself, without hovering over

### ISSUE THREAD

**Issue by vstepaniuk** [jaatroko/link-status-redux#15]
Show link status next to the link itself, without hovering over. is it possible?

**Comment by jaatroko** [comment]
I'm not certain what you mean, could you be more specific?

What I _think_ you mean is that _every_ link in a page should _always_ have a "popup" bubble next to it containing the link status, but why would you want this: it would clutter up some (most?) sites unusable, possibly even unrecognizable.

Also, determining position and size of a link within a page is nontrivial, or at least not as easy as just responding to mouseover events.

**Comment by vstepaniuk** [comment]
Like instead of a bookmarked [link](https://example.com), you could show everywhere [★link](https://example.com)

**Comment by jaatroko** [comment]
It's a nice idea in theory, but there are (at least) two issues which lead to the answer being "won't happen":

1. It would require modifying the page DOM (instead of just adding to it, like with the popup overlay iframe), which is both nontrivial and fragile and thus something I really don't want to do.

1. It would only work properly for plain text links, not for image links etc. And determining whether the link is plain text or not can be nontrivial.
