### ISSUE TITLE
 WebExtension breaks the TiddlyWiki website

### ISSUE THREAD

**Issue by ptheod** [jaatroko/link-status-redux#17]
A big red banner with the message "Internal Javascript Error" appears when clicking any link in the [TiddlyWiki website](https://tiddlywiki.com/).

TiddlyWiki is a javascript wiki running entirely in the browser or through nodejs. So it can form part of everyday workflow (as in my case). Unfortunately, I am not familiar with webextension API at all so I couldn't make any debugging myself. Do you think it is easy to fix?

**Comment by jaatroko** [comment]
Works for me, Firefox 66 and LSR 3.7. You could try with a clean profile and LSR the only addon installed.

**Comment by ptheod** [comment]
You are right! [Clean profile + LSR only] worked for me too.

After disabling one by one the other extensions in my normal profile I found that the problem appears when the extension [Disable HTML5 Autoplay](https://addons.mozilla.org/en-US/firefox/addon/disable-autoplay/) is also installed. Thus [Clean profile + LSR + DisableAutoplay] reproduces the problem.

As a workaround (in case somebody else needs it) I also found that disabling the DisableAutoplay for TiddlyWiki suppresses the problem.

I hope you are willing to have a look/debug the issue although I understand it is probably not your fault. 

Thanks!

**Comment by jaatroko** [comment]
Yep, Disable HTML5 Autoplay's content script tries to capture/modify keyboard/mouse input to the LSR iframe, which fails due to cross-origin, and the error is caught by TiddlyWiki. This type of problem is unfixable, as the iframe _must_ be there to create the overlay element, and thus page scripts and content scripts of other addons can do (or try to do) anything they want with it (see issue #7).

As a side note, if you just want to _always_ disable autoplay, these about:config settings should work for Firefox 66:
`media.autoplay.default = 1`
`media.block-autoplay-until-in-foreground = true`
`media.autoplay.allow-muted = false`

**Comment by ptheod** [comment]
Ok, thanks for the comprehensive answer!

I will also try the config settings for "autoplay"

**Comment by jaatroko** [comment]
Well, turns out that this particular issue can be fixed by hiding the overlay in a shadow DOM (LSR version 3.10, Firefox 63+), though one should keep in mind that shadow DOMs cannot fix all the issues with WebExtension UI elements.
