### ISSUE TITLE
Error in Browser Console 

### ISSUE THREAD

**Issue by Peuj** [jaatroko/link-status-redux#18]
Hello,

I don't if it's bad but when a tab is loading/loaded, I often get this error in the Browser Console 
```
Error: Could not establish connection. Receiving end does not exist.
````
From this line:
https://github.com/jaatroko/link-status-redux/blob/3dac06ad31d3f3a41bae64a9a6fce45502c2c850/webextension/background.js#L388

**Comment by jaatroko** [comment]
As you may have deduced, these are harmless, if a bit ugly cluttering the browser console. And I think you made a mistake in the line number, in my tests the culprit is line 368 (in function send_to_overlay; line 388 should _not_ cause these errors), and as can be seen from the preceding code, the message is sent regeardless of whether the recipient is confirmed ready.

This is the result of trying to solve a hard(ish) asynchronity / race condition problem: how to tell when the recipient is ready (and ready to receive messages) when your only tool is sending messages. So instead of trying to solve this "correctly" and adding code complexity, I just used brute force where applicable, and the only (visible) downside are those error messages in the browser console (which normal users won't ever even see).

(If someone does have a "correct"/better solution that is not overly complicated, I would like to know.)

**Comment by Peuj** [comment]
Hi, I've proposed a PR to solve the errors.
