### ISSUE TITLE
Error on all sites: "Security Error: Content at <url> may not load or link to moz-extension://none/."

### ISSUE THREAD

**Issue by pbarney** [jaatroko/link-status-redux#26]
Every single page I visit produces the following message in the developer tools console window:

> Security Error: Content at <url> may not load or link to moz-extension://none/.

Addon version 3.11
Firefox version 79.0

I had to disable each of my addons one-by-one to determine which one was causing it, and it's definitely link-status-redux.

**Comment by jaatroko** [comment]
I assume that LSR still works, and you are only complaining about the error messages(?) They are an unfortunate (though invisible to "normal" users) side effect of trying to fix site breakage: the link status overlay is an iframe within the page, and though the iframe's src attribute is not used to load the content it needs to be set so that it is effectively valid *and* invalid at the same time to prevent breakage when page javascript appends to it (other modification cannot be defended against). See commit 4ebda74 for details.

However, when using shadow DOM (Firefox 63+, commit 8723691) this should no longer be necessary. I will test with an empty src when using shadow DOM, and if there are no problems I will push an update to AMO.
