### ISSUE TITLE
Link not appearing Inside addon-bar .. .

### ISSUE THREAD

**Issue by xlovinglyx** [jaatroko/link-status-redux#28]
"Waterfox Legacy" V2021.06 + Link Status Redux V2.8

Hi, i installed classic theme restorer to obtain the Addon-bar at the bottom,
but link status redux keeps appearing over/on top of the addon-bar.

How could i fix that with a userstyle or userscript ?  I also found out i could 
update to webextention version in waterfox classic too.

**Comment by jaatroko** [comment]
Interaction between add-ons is a mess, and with the legacy add-ons it is even more so, mostly for the same reasons you could also accomplish more with them, i.e. access to low(ish)-level browser internals. The 2.8 legacy version worked with Status-4-Evar because it was specifically written to work with it (S4E was an add-on I personally used at that time). For a legacy add-on to interact with another (without its cooperation), it needs to:

1. Wait for the other add-on to start and then detect its presence (and give up if not detected within a certain time of startup).
2. Know the internals of the other add-on (which may change between versions).
3. Modify the other add-on's JS/XUL code to achieve what is wanted

I do not think you can accomplish the above without modifying the add-on's code itself. As the legacy version is no longer supported, you will be on your own.
