### ISSUE TITLE
No icon displayed on first new tab opened

### ISSUE THREAD

**Issue by pm64** [jaatroko/link-status-redux#30]
I observed a strange issue recently that I've traced to this excellent add-on: when a new (blank) tab is opened -- and it is either the first tab opened during the browser session, or the first tab opened after link-status-redux has been enabled -- that tab's icon is not displayed. Subsequently opened new tabs display the icon as expected. Disabling link-status-redux resolves the issue.

![image](https://user-images.githubusercontent.com/10715458/121783998-50f0e780-cb66-11eb-98fe-2a38a0e763ec.png)

**Comment by jaatroko** [comment]
Now that you mention it, I remember seeing this myself and wondering why it happens, but thinking it is just some Firefox weirdness. And in a way it is: after some poking around I found out that this can be reproduced with a clean profile with no add-ons by setting new tabs to a blank page, opening a new tab, and then _reloading_ the blank page. The realoding cannot be done by normal means, you need to use one of the following:

1. Type "about:blank" to the address bar and press enter.
2. Open the developer tools with F12 and press the reload button in the network tab.

So it seems that _about:blank_, which is the content page for new tabs (if so configured), does not have a favicon, but Firefox does use its own favicon for a new tab page initially. So it seems that this is some kind of race condition that _sometimes_ causes the new tab content to be reloaded, at least conceptually, which in turn makes the favicon disappear. I have no idea how/why LSR causes this to happen.

However, since this is just a mild cosmetic flaw _and_ the use case for new blank tabs is transient (i.e. one is only opened to immediately type/copy-paste a URL into the address bar), this should not bother anyone overmuch and thus I won't even try to figure out why it happens.
