### ISSUE TITLE
Feature Request: show whether the destination is currently open in another tab

### ISSUE THREAD

**Issue by hmijail** [jaatroko/link-status-redux#31]
It would be useful to have an indication of whether the hovered-over link is currently open in another tab. There's a number of add-ons for duplicate tab detection/closing, but warning the user _before_ the duplicate tab is opened might be more useful than reacting afterwards.

**Comment by jaatroko** [comment]
After a quick look at the API this should be fairly easy to implement, so I will take a look at it when I have time.

However, there are (at least) two cases where this may not work as wanted/imagined:

 1. Redirections. It is very common practice to redirect from a http site to the corresponding https site. If the link points to the http site, then it will never show as open in a tab because the tab will have the https site instead. And as the http and https sites are not _required_ to be the same site (this is more obvious if the redirection is cross-domain), it cannot/shouldn't be compensated by ignoring the http(s) part. (IIRC the redirections are stored in the history, so the link will still show as visited.)
 
 2. URI fragments. While `page.html` and `page.html#section1` point to the same document (fragments are not sent to the server), the content can be entirely different if that "document" is a webapp. This means that either case can be argued to be correct, so I'm probably _not_ going to ignore fragments in the URL matching.

**Comment by hmijail** [comment]
Wow, that was educative. Thank you lots, both for your answer and your work!

**Comment by jaatroko** [comment]
The github master branch now has this functionality (*without* option UI, force-enabled in "normal" mode, angle brackets (e.g. `%+<%O%+>`) in custom formatting). You can test it by downloading the source code and loading a temporary add-on via `about:debugging` -> This Firefox -> Load Temporary Add-on... -> (select the `manifest.json` file). Though caution is advised: I'm not 100% certain that the add-on preferences won't be corrupted when switching between newer/temporary and permanent versions, so maybe backup your preferences or use another profile.

I need to ponder a bit more about the options UI, and then it will need to get translated to the languages currently supported, so it will still take time before an official release.

**Comment by jaatroko** [comment]
It took a while, but version 3.13 with this feature is now available from AMO. The feature is disabled by default, as it has the above-mentioned problems with false positives.
