### ISSUE TITLE
Feature request: show indication if page has been previously visited

### ISSUE THREAD

**Issue by mkbloke** [jaatroko/link-status-redux#32]
### Scenario:

Let's say I get emails from organisation X.  Those emails don't link directly to the organisation's content, they are redirected via a third party link tracking system.

I use ClearURLs to get clean base URLs, e.g. https://www.x.tld/path/to/content instead of https://www.x.tld/path/to/content?tracking_param=somerandomstring.

If I have already read an article at a given URL, for example, https://www.x.tld/path/to/article, I don't know that because of the third party link tracking link in the email.

### Proposed feature request:

Some indication when the page is loaded either in the same tab or a new tab, that has been visited before.  Given that I tend to open new tabs to content without switching to that tab immediately, it would also be useful if the method used to display the previously visited information accommodate this also.

### Possible solution:

~The previously visited information (if it is so), is injected into the newly opened page to display a pop-up similar to the default method used for links as is currently done.  The position could perhaps be configurable, although top-right or page centred would be good for me.  This pop-up would be displayed for a limited time (maybe a configurable number of seconds) and that timer would not start until the tab became active to accommodate tabs that have been opened but are not switched to immediately.~

Edited because upon thinking more about this, I've realised a pop-up would rapidly become very annoying for pages you visit regularly.

I think a better and far less annoying solution would be a toolbar item to convey this information.

I hope that sounds reasonable.  Many thanks for a great add-on, I'm finding it very useful as is.

**Comment by jaatroko** [comment]
I tested with ClearURLs installed, using the example Amazon link at ClearURLs' home page (copied to a local test page), and after clicking it the link showed as visited when hovered over. It seems that ClearURLs inserts the original URL into the browser history before loading the cleaned URL. It is also standard Firefox behavior to insert the intermediate steps in a redirection chain into the history. So the scenario you describe should not exist? Or do you mean that the tracking IDs etc. change (between two emails) but the link target is still effectively the same, in which case it has nothing to do with ClearURLs.

Anyway, if I understand correctly, you want the following to happen: when the page has finished loading, check whether it has been previously visited more than ~10s ago (to exclude the current tab's visit), and if so, show a limited-lifetime information banner/textbox when the tab is activated (or immediately if already active). The idea is not without merit, but it is a bit out of scope for LSR, or just barely within: the main purpose of LSR is to make an informed decision _before_ opening a link. If you already have opened the link, it should usually be quickly obvious from the page content whether or not you have visited it before, and/or whether or not it has changed to warrant re-reading. I will have to think about this more, so not _immediately_ rejected, but don't hold your breath either.

Here are some problems/questions I came up with:

- Should the banner be shown only for newly created tabs, or also for subsequent content loads within the tab (page reload, following a link, typing a new URL)? I'm not sure if those are distinguishable to webextensions, but I would guess so.

- Most people have many pages they visit regularly and frequently (front pages of news/blogs/etc.). For those pages the banner could/would just be a nuisance (and implementing allow/block lists is also a bother). (Ah, I see you realized this and edited your comment. As for the toolbar item: LSR does not have a toolbar icon, and I'm _very_ reluctant to add one, as I want to keep the addon as unobtrusive as possible.)

- If you open the same unvisited link in two tabs, only the second one will show the banner. Then you (for some reason) close the first one without reading it. And then when you come to the second one you see the banner and immediately close it, thus never reading the page. A bit contrived example, but not entirely impossible.

- Related to the above two points: though I can't right now think of additional concrete examples, what I'm mainly worried about is that due to the ordering and timing of browser or user actions the banner ends up showing false (or useless/nuisance) information.

**Comment by mkbloke** [comment]
Thank you for your reply.

You're right that ClearURLs is not really relevant to the issue raised.  It was unnecessary on my part to include that information.  My apologies.

If I have visited a URL directly on a site at say, https://x.tld/path/to/article-a and that article is then linked to subsequently in an email via a tracking service, that tracking link will not show as visited (as would be expected), unless it has previously been visited via the same tracking URL.  I would have thought these tracking URLs could (are likely to?) be different in each email sent, allowing not only tracking by user, but tracking by email sent even if multiple emails link to the same eventual target URL.  The problem (for me!) is that it can take a bit of reading of an article before I might realise that I've read it previously, so having some rapid indication of a prior visit based on the eventual URL arrived at would be useful.

I appreciate your view on keeping LSR as unobtrusive as possible.  Also, now that you have mentioned it, I think what I am asking for is out of scope for LSR.  As a result, I think perhaps it might be better for me to seek an alternative solution.  I can look through other add-ons to see if there's anything that might help, or failing that, I could probably piece together a simple custom add-on to do the job by looking at code from other add-ons and doing some Stack Overflow based software development,,,

You raise some interesting points and I think I will have to ponder those while thinking more about how this might work.  Either that or work on improving my memory!  Given what I've said in the previous paragraph, I will close this request as I don't think what I want is a suitable fit for LSR.

Many thanks for your time and for creating a great add-on.

**Comment by mkbloke** [comment]
Just to add to this (for anybody who comes across this in future), I have found a little used add-on called 'Visit History' that is fine for my needs.  It adds a page action icon to the URL bar in Firefox, which when clicked will display previous visit info.  The source is on GitHub too, which I happen to like.  In combination with LSR it's great.

https://addons.mozilla.org/en-GB/firefox/addon/visit-history/
https://github.com/hoelzro/fx-visit-history
